work

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -19,8 +19,16 @@ command -v psql >/dev/null 2>&1 || {
 echo "==> Installing python packages"
 pipenv install -d
 
+[ -f .env ] || {
+    echo >&2 "Cannot find .env file."
+    echo >&2 "Copy .env.sample to .env and fill out with your database details"
+    exit 1
+}
+
+. .env
+
 echo "==> Creating user"
-createuser kerascallback 2>/dev/null || true
+createuser $TEST_USER 2>/dev/null || true
 
 echo "==> Creating database"
-createdb kerascallback_dev -O kerascallback 2>/dev/null || true
+createdb $TEST_DB -O $TEST_USER 2>/dev/null || true
